version: "3"

services:
  j4u-postgres:
    container_name: j4u-postgres
    image: postgres:11-alpine
    restart: "no"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
