"""empty message

Revision ID: 056ad317c517
Revises: 
Create Date: 2020-04-05 22:27:26.445434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '056ad317c517'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('var1', sa.Float(), nullable=False),
    sa.Column('var2', sa.Float(), nullable=False),
    sa.Column('var3', sa.Float(), nullable=False),
    sa.Column('var4', sa.Float(), nullable=False),
    sa.Column('var5', sa.Float(), nullable=False),
    sa.Column('var6', sa.Float(), nullable=False),
    sa.Column('var7', sa.Float(), nullable=False),
    sa.Column('var8', sa.Float(), nullable=False),
    sa.Column('var9', sa.Float(), nullable=False),
    sa.Column('var10', sa.Float(), nullable=False),
    sa.Column('var11', sa.Float(), nullable=False),
    sa.Column('var12', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('baseline_id', sa.String(length=64), nullable=True),
    sa.Column('cruiser_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='roleenum'), nullable=True),
    sa.Column('civilite', sa.Enum('M', 'MLLE', 'MME', name='civiliteenum'), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('form_done', sa.Boolean(), nullable=True),
    sa.Column('survey_id', sa.String(length=10), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('alpha', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('old_job_id', sa.Integer(), nullable=True),
    sa.Column('features_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['features_id'], ['features.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('features_id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('survey_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('groups')
    op.drop_table('features')
    # ### end Alembic commands ###
