"""empty message

Revision ID: 282487fb746f
Revises: 
Create Date: 2020-04-25 13:32:07.259156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282487fb746f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qualtrics_name', sa.String(length=64), nullable=False),
    sa.Column('engine_name', sa.String(length=64), nullable=False),
    sa.Column('from_min', sa.Integer(), nullable=False),
    sa.Column('from_max', sa.Integer(), nullable=False),
    sa.Column('to_min', sa.Integer(), nullable=False),
    sa.Column('to_max', sa.Integer(), nullable=False),
    sa.Column('inverse', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('engine_name'),
    sa.UniqueConstraint('qualtrics_name')
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('baseline_id', sa.String(length=64), nullable=True),
    sa.Column('cruiser_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avam', sa.Integer(), nullable=False),
    sa.Column('bfs', sa.Integer(), nullable=False),
    sa.Column('isco08', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('isco_title', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('jobs_unique_index', 'jobs', ['avam', 'bfs', 'isco08', 'title'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='roleenum'), nullable=True),
    sa.Column('civilite', sa.Enum('M', 'MLLE', 'MME', name='civiliteenum'), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('form_done', sa.Boolean(), nullable=True),
    sa.Column('form_done_at', sa.Date(), nullable=True),
    sa.Column('survey_id', sa.String(length=10), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('alpha', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('old_job_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('survey_id')
    )
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('feature_config_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['feature_config_id'], ['feature_configs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('features')
    op.drop_table('users')
    op.drop_index('jobs_unique_index', table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('groups')
    op.drop_table('feature_configs')
    # ### end Alembic commands ###
