"""empty message

Revision ID: f9470650ccd4
Revises: 
Create Date: 2020-03-28 13:15:04.219532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9470650ccd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='roleenum'), nullable=True),
    sa.Column('civilite', sa.Enum('M', 'MLLE', 'MME', name='civiliteenum'), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('formDone', sa.Boolean(), nullable=True),
    sa.Column('survey_id', sa.String(length=10), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('alpha', sa.Float(), nullable=True),
    sa.Column('beta', sa.Float(), nullable=True),
    sa.Column('oldJobValue', sa.Integer(), nullable=True),
    sa.Column('oldJobLabel', sa.String(length=100), nullable=True),
    sa.Column('group', sa.Enum('COG', 'CONT', 'J4U', 'J4UCOG', 'NJS', 'J4UNJS', name='groupenum'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('survey_id')
    )
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('var1', sa.Float(), nullable=False),
    sa.Column('var2', sa.Float(), nullable=False),
    sa.Column('var3', sa.Float(), nullable=False),
    sa.Column('var4', sa.Float(), nullable=False),
    sa.Column('var5', sa.Float(), nullable=False),
    sa.Column('var6', sa.Float(), nullable=False),
    sa.Column('var7', sa.Float(), nullable=False),
    sa.Column('var8', sa.Float(), nullable=False),
    sa.Column('var9', sa.Float(), nullable=False),
    sa.Column('var10', sa.Float(), nullable=False),
    sa.Column('var11', sa.Float(), nullable=False),
    sa.Column('var12', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('features')
    op.drop_table('users')
    # ### end Alembic commands ###
